[tasks.default]
clear = true
command = "echo"
args = [
    "\n",
    "************************\n",
    "USAGE:\n",
    " build: Build the project.\n",
    " run: Run the windows-exe file after building it.\n",
    "************************\n",
]


[tasks.prepare-to-build]
run_task = { name = ["copy-src", "copy-assets"] }

[tasks.prepare-directories-src]
command = "mkdir"
args = ["-p", "src/embedded_assets/fonts"]

[tasks.prepare-directories-assets]
command = "mkdir"
args = ["-p", "assets/fonts"]

[tasks.copy-src]
command = "cp"
args = ["--update",
    "external/GL-CurulMinamoto/fonts/ttf/GL-CurulMinamoto.ttf",
    "external/x12y12pxMaruMinyaM/x12y12pxMaruMinyaM.ttf",
    "src/embedded_assets/fonts/",
]
dependencies = ["prepare-directories-src"]

[tasks.copy-assets]
command = "cp"
args = ["--update",
    "external/GL-CurulMinamoto/fonts/ttf/GL-CurulMinamoto.ttf",
    "external/x12y12pxMaruMinyaM/x12y12pxMaruMinyaM.ttf",
    "assets/fonts/",
]
dependencies = ["prepare-directories-assets"]



[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["prepare-to-build"]

[tasks.run]
run_task = { name = ["prepare-to-run", "run-exe", "post-run"] }

[tasks.prepare-to-run]
command = "cp"
args = ["target/x86_64-pc-windows-msvc/debug/suika_clone.exe", "./"]
dependencies = ["build"]

[tasks.run-exe]
command = "./suika_clone.exe"

[tasks.post-run]
command = "rm"
args = ["./suika_clone.exe"]



[tasks.build-web]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown"]
dependencies = ["prepare-to-build"]

[tasks.run-web]
command = "cargo"
args = ["run", "--target", "wasm32-unknown-unknown"]
dependencies = ["build-web"]

