[package]
name = "game_ron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
ron = { workspace = true }
serde = { workspace = true}
