name: build-recent
on:
  push:
    branches: [ "main" ]
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Get rust toolchain for wasm32
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true
      - name: Get rust toolchain for windows(gnu)
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-gnu
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
      - name: Get mingw
        # uses: egor-tensin/setup-mingw@v2
        run: sudo apt install -y gcc-mingw-w64-x86-64 mingw-w64-x86-64-dev
      - name: Build release(windows-gnu)
        run: cargo make --cwd suika_clone/ release-win-gnu
      - name: Zip windows build
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'suika_clone_x86_64-windows-gnu.zip'
          path: out-win
      - name: Build release(wasm32)
        run: cargo make --cwd suika_clone/ release-web
      - name: Make out
        run: mkdir out
      - name: Move web-build contents
        run: cp -r out-web/* ./out/
      - name: Move windows-build
        run: cp suika_clone_x86_64-windows-gnu.zip ./out/
      - uses: actions/upload-artifact@v4
        with:
          name: suika_clone
          path: out
          if-no-files-found: error
      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build-release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
